spring:
  datasource:
    url: jdbc:mysql://localhost:3312/omniguardy_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=utf8
    username: team3
    password: omniguardy_pw
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true # SQL을 예쁘게 줄바꿈해서 보여줌

server:
  port: 8080

jwt:
  secret-key: omniguardy-secret-key-should-be-at-least-32-bytes
  access-token-expire-time: 1800000       # 30분
  refresh-token-expire-time: 1209600000  # 14일

mqtt:
  broker-url: tcp://10.254.2.174:1883 #라즈베리파이 ip
  client-id: omniguardy-backend
  topic:
    tts: door/tts

app:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  tts:
    audio-dir: ./_vol/tts/audio
    audio-url-prefix: /audio/tts